included:
- JXWebViewController

disabled_rules:
- cyclomatic_complexity
- file_length
- function_body_length
- line_length
- type_body_length

opt_in_rules:
- array_init
- attributes
- closure_end_indentation
- closure_spacing
- contains_over_first_not_nil
- discouraged_object_literal
- explicit_init
- extension_access_modifier
- fatal_error_message
- first_where
- force_unwrapping
- implicit_return
- joined_default_parameter
- let_var_whitespace
- literal_expression_end_indentation
- multiline_arguments
- multiline_parameters
- nimble_operator
- no_extension_access_modifier
- number_separator
- operator_usage_whitespace
- overridden_super_call
- override_in_extension
- pattern_matching_keywords
- prefixed_toplevel_constant
- private_action
- private_outlet
- quick_discouraged_call
- quick_discouraged_focused_test
- quick_discouraged_pending_test
- redundant_nil_coalescing
- required_enum_case
- single_test_class
- sorted_first_last
- sorted_imports
- strict_fileprivate
- switch_case_on_newline
- trailing_closure
- unneeded_parentheses_in_closure_argument
- vertical_parameter_alignment_on_call
- yoda_condition

trailing_comma:
  mandatory_comma: true
